name: CI - Gestión Productos Reactivo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar Maven
        run: mvn --version

      - name: Construir el proyecto
        run: mvn clean package

      - name: Ejecutar pruebas
        run: mvn test